"""Config and options flows for the EV Charging Log companion."""

from __future__ import annotations

from typing import Any

import voluptuous as vol

from homeassistant.components.recorder import get_instance
from homeassistant.config_entries import (
    ConfigEntry,
    ConfigFlow,
    ConfigFlowResult,
    OptionsFlow,
)
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.selector import (
    EntitySelector,
    EntitySelectorConfig,
    TextSelector,
    TextSelectorConfig,
    TextSelectorType,
)

from .const import (
    CONF_ODOMETER_ENTITY,
    CONF_SECRET,
    CONF_SECRET_HASH,
    CONF_TELEMETRY_ENTITY,
    DOMAIN,
    MIN_SECRET_LENGTH,
)
from .view import hash_secret

TITLE = "EV Charging Log companion"

_SECRET_SELECTOR = TextSelector(TextSelectorConfig(type=TextSelectorType.PASSWORD))


def _entity_schema(defaults: dict[str, Any]) -> dict[vol.Marker, Any]:
    return {
        vol.Required(
            CONF_ODOMETER_ENTITY, default=defaults.get(CONF_ODOMETER_ENTITY, vol.UNDEFINED)
        ): EntitySelector(EntitySelectorConfig(domain="sensor", device_class="distance")),
        vol.Required(
            CONF_TELEMETRY_ENTITY,
            default=defaults.get(CONF_TELEMETRY_ENTITY, vol.UNDEFINED),
        ): EntitySelector(EntitySelectorConfig(domain="sensor", device_class="timestamp")),
    }


def _validate(user_input: dict[str, Any], secret_required: bool) -> dict[str, str]:
    errors: dict[str, str] = {}
    if user_input[CONF_ODOMETER_ENTITY] == user_input[CONF_TELEMETRY_ENTITY]:
        errors["base"] = "same_entity"
    secret = (user_input.get(CONF_SECRET) or "").strip()
    if (secret or secret_required) and len(secret) < MIN_SECRET_LENGTH:
        errors[CONF_SECRET] = "secret_too_short"
    return errors


def _unrecorded(hass: HomeAssistant, entity_ids: list[str]) -> list[str]:
    """Entities the recorder's include/exclude filter leaves out."""
    entity_filter = getattr(get_instance(hass), "entity_filter", None)
    if not callable(entity_filter):
        return []
    return [entity_id for entity_id in entity_ids if not entity_filter(entity_id)]


class EvChargingLogConfigFlow(ConfigFlow, domain=DOMAIN):
    """Pick the two entities and paste the secret generated by the app."""

    VERSION = 1

    def __init__(self) -> None:
        """Hold validated data while the recorder warning is shown."""
        self._data: dict[str, Any] = {}

    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        """Handle the only setup step."""
        errors: dict[str, str] = {}
        if user_input is not None:
            errors = _validate(user_input, secret_required=True)
            if not errors:
                # Only the hash is stored. The secret itself never touches disk.
                self._data = {
                    CONF_ODOMETER_ENTITY: user_input[CONF_ODOMETER_ENTITY],
                    CONF_TELEMETRY_ENTITY: user_input[CONF_TELEMETRY_ENTITY],
                    CONF_SECRET_HASH: hash_secret(user_input[CONF_SECRET].strip()),
                }
                if _unrecorded(
                    self.hass,
                    [self._data[CONF_ODOMETER_ENTITY], self._data[CONF_TELEMETRY_ENTITY]],
                ):
                    return await self.async_step_not_recorded()
                return self.async_create_entry(title=TITLE, data=self._data)

        schema = vol.Schema(
            {
                **_entity_schema(user_input or {}),
                vol.Required(CONF_SECRET): _SECRET_SELECTOR,
            }
        )
        return self.async_show_form(step_id="user", data_schema=schema, errors=errors)

    async def async_step_not_recorded(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Warn that an excluded entity will come back with no history."""
        if user_input is not None:
            return self.async_create_entry(title=TITLE, data=self._data)
        missing = _unrecorded(
            self.hass,
            [self._data[CONF_ODOMETER_ENTITY], self._data[CONF_TELEMETRY_ENTITY]],
        )
        return self.async_show_form(
            step_id="not_recorded",
            description_placeholders={"entities": ", ".join(missing)},
        )

    @staticmethod
    @callback
    def async_get_options_flow(config_entry: ConfigEntry) -> OptionsFlow:
        """Rotate the secret or change the entities."""
        return EvChargingLogOptionsFlow()


class EvChargingLogOptionsFlow(OptionsFlow):
    """Leave the secret blank to keep the current one."""

    async def async_step_init(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        """Handle the options step."""
        errors: dict[str, str] = {}
        current = self.config_entry.data
        if user_input is not None:
            errors = _validate(user_input, secret_required=False)
            if not errors:
                data = {
                    **current,
                    CONF_ODOMETER_ENTITY: user_input[CONF_ODOMETER_ENTITY],
                    CONF_TELEMETRY_ENTITY: user_input[CONF_TELEMETRY_ENTITY],
                }
                if secret := (user_input.get(CONF_SECRET) or "").strip():
                    data[CONF_SECRET_HASH] = hash_secret(secret)
                # Takes effect on the next request: the view reads entry.data live.
                self.hass.config_entries.async_update_entry(self.config_entry, data=data)
                return self.async_create_entry(data={})

        schema = vol.Schema(
            {
                **_entity_schema(user_input or current),
                vol.Optional(CONF_SECRET): _SECRET_SELECTOR,
            }
        )
        return self.async_show_form(step_id="init", data_schema=schema, errors=errors)
